### ISSUE TITLE
sniffles require MD

### ISSUE THREAD

**Issue by projectoriented** [EichlerLab/ONT_pipelines#1] opened 2022-11-08 22:05 UTC
Hello 👋 ,

I got this error when the pipeline runs sniffles:
```
Estimating parameter...
No MD string detected! Check bam file! Otherwise generate using e.g. samtools.
```
I'll make a pull request & add `--MD` to the minimap2 argument

**Comment by projectoriented** [comment] 2022-11-08 22:06
Oh, hmm I see that flag is already included in the minimap2 command 🤔

**Comment by projectoriented** [comment] 2022-11-08 22:34
This is one entry of the pipeline's merged bam
```
fad02af8-5bcf-46b9-abcb-47c6ce3e8873	2048	chr1	958	60	3817H4M1I6M1I8M1D9M1I2M2I34M1I32M1D27M2448H	*	0	0	CCCTCCACCCTCCACCCTCACCTCACCCTCCACCCCCTCACCCTCACCCTCACCCTCACCCTCACCCTCCACCCTAACCCTCACCCTCACCCTCACCCTCACCTCACCCTCACCCTCACCCTCACCCT	%&'(.*&%')(/+))-3.5*(())*78:68.,,17/.37788;<=0//7/62229791002(12657+3*))*3-/19<><=888;372---)522254;0//+*.,,0-4/.-105.--..30,*0/	NM:i:9	ms:i:195	AS:i:194	nn:i:0	tp:A:P	cm:i:7	s1:i:64	s2:i:132	de:f:0.062	zd:i:1	SA:Z:chr7,160563287,-,17S1955M395D4421S,60,808;	rl:i:105
```

This is the same entry after I've added MD tags w/ `samtools calmd`
```
fad02af8-5bcf-46b9-abcb-47c6ce3e8873	2048	chr1	958	60	3817H4M1I6M1I8M1D9M1I2M2I34M1I32M1D27M2448H	*	0	0	CCCTCCACCCTCCACCCTCACCTCACCCTCCACCCCCTCACCCTCACCCTCACCCTCACCCTCACCCTCCACCCTAACCCTCACCCTCACCCTCACCCTCACCTCACCCTCACCCTCACCCTCACCCT	%&'(.*&%')(/+))-3.5*(())*78:68.,,17/.37788;<=0//7/62229791002(12657+3*))*3-/19<><=888;372---)522254;0//+*.,,0-4/.-105.--..30,*0/	NM:i:9	ms:i:195	AS:i:194	nn:i:0	tp:A:P	cm:i:7	s1:i:64	s2:i:132	de:f:0.062	zd:i:1	SA:Z:chr7,160563287,-,17S1955M395D4421S,60,808;	rl:i:105	MD:Z:18^C51C25^C27
```

Let me know if you want me to make a rule calling `samtools calmd` & then I'll submit a PR. Thanks!

**Comment by wharvey31** [comment] 2023-01-31 00:33
Caused by a de-sync between the repo and cluster software. Fixed now!

**Closed as completed by wharvey31** 2023-01-31 00:33 UTC
